#========================================
# TASKS - use the cargo-make plugin 
# (cargo install --force cargo-make)
#========================================

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build_dev]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.build_release]
command = "cargo"
args = ["build","--release"]
dependencies = ["clean"]


[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.all_dev]
dependencies = [
    "format",
    "build_dev",
    "test"
]

[tasks.all_release]
dependencies = [
    "format",
    "build_release",
    "test"
]