use crate::synth::utils::converters::*;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize,Clone)]
pub enum Note {
  C0,CS0,D0,DS0,E0,F0,FS0,G0,GS0,A0,AS0,B0,
  C1,CS1,D1,DS1,E1,F1,FS1,G1,GS1,A1,AS1,B1,
  C2,CS2,D2,DS2,E2,F2,FS2,G2,GS2,A2,AS2,B2,
  C3,CS3,D3,DS3,E3,F3,FS3,G3,GS3,A3,AS3,B3,
  C4,CS4,D4,DS4,E4,F4,FS4,G4,GS4,A4,AS4,B4,
  C5,CS5,D5,DS5,E5,F5,FS5,G5,GS5,A5,AS5,B5,
  C6,CS6,D6,DS6,E6,F6,FS6,G6,GS6,A6,AS6,B6,
  C7,CS7,D7,DS7,E7,F7,FS7,G7,GS7,A7,AS7,B7,
  C8,CS8,D8,DS8,E8,F8,FS8,G8,GS8,A8,AS8,B8,
  C9,CS9,D9,DS9,E9,F9,FS9,G9,GS9,A9,AS9,B9,
  C10,CS10,D10,DS10,E10,F10,FS10,G10,GS10,A10,AS10,B10
}

impl Note {
  pub fn to_voltage(&self) -> f32 {
    match self {
      Note::C0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B0 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B1 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B2 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B3 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B4 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B5 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B6 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B7 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B8 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B9 => midi_to_voltage(self.to_midi_note() as f32),
      Note::C10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::CS10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::D10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::DS10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::E10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::F10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::FS10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::G10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::GS10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::A10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::AS10 => midi_to_voltage(self.to_midi_note() as f32),
      Note::B10 => midi_to_voltage(self.to_midi_note() as f32)
    }
  }
  pub fn to_midi_note(&self) -> i32 {
    match self {
      Note::C0 => 12, 
      Note::CS0 => 13, 
      Note::D0 => 14, 
      Note::DS0 => 15, 
      Note::E0 => 16, 
      Note::F0 => 17, 
      Note::FS0 => 18, 
      Note::G0 => 19, 
      Note::GS0 => 20, 
      Note::A0 => 21, 
      Note::AS0 => 22, 
      Note::B0 => 23, 
      Note::C1 => 24, 
      Note::CS1 => 25, 
      Note::D1 => 26, 
      Note::DS1 => 27, 
      Note::E1 => 28, 
      Note::F1 => 29, 
      Note::FS1 => 30, 
      Note::G1 => 31, 
      Note::GS1 => 32, 
      Note::A1 => 33, 
      Note::AS1 => 34, 
      Note::B1 => 35, 
      Note::C2 => 36, 
      Note::CS2 => 37, 
      Note::D2 => 38, 
      Note::DS2 => 39, 
      Note::E2 => 40, 
      Note::F2 => 41, 
      Note::FS2 => 42, 
      Note::G2 => 43, 
      Note::GS2 => 44, 
      Note::A2 => 45, 
      Note::AS2 => 46, 
      Note::B2 => 47, 
      Note::C3 => 48, 
      Note::CS3 => 49, 
      Note::D3 => 50, 
      Note::DS3 => 51, 
      Note::E3 => 52, 
      Note::F3 => 53, 
      Note::FS3 => 54, 
      Note::G3 => 55, 
      Note::GS3 => 56, 
      Note::A3 => 57, 
      Note::AS3 => 58, 
      Note::B3 => 59, 
      Note::C4 => 60, 
      Note::CS4 => 61, 
      Note::D4 => 62, 
      Note::DS4 => 63, 
      Note::E4 => 64, 
      Note::F4 => 65, 
      Note::FS4 => 66, 
      Note::G4 => 67, 
      Note::GS4 => 68, 
      Note::A4 => 69, 
      Note::AS4 => 70, 
      Note::B4 => 71, 
      Note::C5 => 72, 
      Note::CS5 => 73, 
      Note::D5 => 74, 
      Note::DS5 => 75, 
      Note::E5 => 76, 
      Note::F5 => 77, 
      Note::FS5 => 78, 
      Note::G5 => 79, 
      Note::GS5 => 80, 
      Note::A5 => 81, 
      Note::AS5 => 82, 
      Note::B5 => 83, 
      Note::C6 => 84, 
      Note::CS6 => 85, 
      Note::D6 => 86, 
      Note::DS6 => 87, 
      Note::E6 => 88, 
      Note::F6 => 89, 
      Note::FS6 => 90, 
      Note::G6 => 91, 
      Note::GS6 => 92, 
      Note::A6 => 93, 
      Note::AS6 => 94, 
      Note::B6 => 95, 
      Note::C7 => 96, 
      Note::CS7 => 97, 
      Note::D7 => 98, 
      Note::DS7 => 99, 
      Note::E7 => 100, 
      Note::F7 => 101, 
      Note::FS7 => 102, 
      Note::G7 => 103, 
      Note::GS7 => 104, 
      Note::A7 => 105, 
      Note::AS7 => 106, 
      Note::B7 => 107, 
      Note::C8 => 108, 
      Note::CS8 => 109, 
      Note::D8 => 110, 
      Note::DS8 => 111, 
      Note::E8 => 112, 
      Note::F8 => 113, 
      Note::FS8 => 114, 
      Note::G8 => 115, 
      Note::GS8 => 116, 
      Note::A8 => 117, 
      Note::AS8 => 118, 
      Note::B8 => 119, 
      Note::C9 => 120, 
      Note::CS9 => 121, 
      Note::D9 => 122, 
      Note::DS9 => 123, 
      Note::E9 => 124, 
      Note::F9 => 125, 
      Note::FS9 => 126, 
      Note::G9 => 127, 
      Note::GS9 => 128, 
      Note::A9 => 129, 
      Note::AS9 => 130, 
      Note::B9 => 131, 
      Note::C10 => 132, 
      Note::CS10 => 133, 
      Note::D10 => 134, 
      Note::DS10 => 135, 
      Note::E10 => 136, 
      Note::F10 => 137, 
      Note::FS10 => 138, 
      Note::G10 => 139, 
      Note::GS10 => 140, 
      Note::A10 => 141, 
      Note::AS10 => 142, 
      Note::B10 => 143
    }
  }
}

